skip_branch_with_pr: true

image:
  - Visual Studio 2019
  - ubuntu

cache:
  - c:\tools\vcpkg\installed\

install:
  - pwsh: |
      if ($isLinux) {
        ./linux/install.ps1
      } else {
        ./windows/install.ps1
      }

build_script:
  - pwsh: |
      if ($isLinux) {
        ./linux/build.ps1
      } else {
        ./windows/build.ps1 -VcpkgToolchain c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake
      }

after_build:
  - pwsh: |
      if ($isLinux) {
        ./linux/pack.ps1
      } else {
        ./windows/pack.ps1
      }

test_script:
  - pwsh: |
      if ($isLinux) {
        ./linux/copy-artifacts.ps1
        ./common/nuget-pack.ps1 -Version "1.7.0.$env:APPVEYOR_BUILD_NUMBER" -UseMono -NuGet "$env:APPVEYOR_BUILD_FOLDER/tools/nuget.exe"
        ./common/test.ps1 -UseMono -NuGet "$env:APPVEYOR_BUILD_FOLDER/tools/nuget.exe"
      } else {
        ./windows/copy-artifacts.ps1
        ./common/nuget-pack.ps1 -Version "1.7.0.$env:APPVEYOR_BUILD_NUMBER"
        ./common/test.ps1
      }

artifacts:
  - path: tdlib.windows.zip
    name: tdlib.windows
  - path: tdlib.linux.zip
    name: tdlib.linux

deploy:
  provider: GitHub
  auth_token:
    secure: gZMcwBPRuLO7UnRn8zrJOh52yLST5z0klrMZg9zsVVMungWPacvh8dOqBj+mkdeV
  artifact: tdlib.windows,tdlib.linux
  on:
    APPVEYOR_REPO_TAG: true
