name: Main
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: macos-10.15
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      # Build:
      - name: Install
        shell: pwsh
        run: ./macos/install.ps1
      - name: Build
        shell: pwsh
        run: ./macos/build.ps1
      - name: Prepare Artifact
        shell: pwsh
        run: ./macos/prepare-artifact.ps1 # produces artifacts/libtdjson.dylib

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: tdlib.osx
          path: artifacts/*

      # Test
      - name: Copy artifacts
        shell: pwsh
        run: ./macos/copy-artifacts.ps1
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.x'
      - name: Pack NuGet
        shell: pwsh
        run: ./common/nuget-pack.ps1 -Version "1.6.0.${{ github.run_id }}" -NuGet nuget

      - name: NuGet cache
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('tdsharp/**/*.csproj') }}
      - name: Test
        shell: pwsh
        run: ./common/test.ps1 -NuGet nuget

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    needs: main
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v2
        with:
          name: tdlib.osx
          path: ./artifacts/osx

      - name: Read version from ref
        id: version
        shell: pwsh
        run: Write-Output "::set-output name=version::$($env:GITHUB_REF -replace '^refs/tags/v', '')"
      - name: Create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ steps.version.outputs.version }}
          draft: true

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: tdlib.osx.zip
          asset_path: ./artifacts/osx/*
