name: Main
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container: ubuntu:18.04
    steps:
      - name: Set up Git
        run: apt-get update && apt-get install -y software-properties-common && apt-get update && add-apt-repository -y ppa:git-core/ppa && apt-get update && apt-get install -y git

      # See this: https://github.blog/2022-04-12-git-security-vulnerability-announced/
      #
      # If this step is not performed, then verify-encoding will fail.
      - name: Set up Git safe directory
        run: git config --global --add safe.directory /__w/tdlib.native/tdlib.native

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up PowerShell
        run: sh ./linux/install-pwsh.sh

      # Verify:
      - name: Verify encoding
        shell: pwsh
        run: ./common/verify-encoding.ps1

      # Build:
      - name: Install
        shell: pwsh
        run: ./linux/install.ps1 -ForBuild
      - name: Build
        shell: pwsh
        run: ./linux/build.ps1
      - name: Prepare artifact
        shell: pwsh
        run: ./linux/prepare-artifact.ps1 # produces artifacts/libtdjson.so

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: tdlib.linux
          path: artifacts/*

  build-macos:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      # Verify:
      - name: Verify encoding
        shell: pwsh
        run: ./common/verify-encoding.ps1

      # Build:
      - name: Install
        shell: pwsh
        run: ./macos/install.ps1
      - name: Build
        shell: pwsh
        run: ./macos/build.ps1
      - name: Prepare Artifact
        shell: pwsh
        run: ./macos/prepare-artifact.ps1 # produces artifacts/libtdjson.dylib

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: tdlib.osx
          path: artifacts/*

  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      # Verify:
      - name: Verify encoding
        shell: pwsh
        run: ./common/verify-encoding.ps1

      # Build:
      - name: Install
        shell: pwsh
        run: ./windows/install.ps1
      - name: Build
        shell: pwsh
        run: ./windows/build.ps1 -VcpkgToolchain c:\vcpkg\scripts\buildsystems\vcpkg.cmake
      - name: Prepare Artifact
        shell: pwsh
        run: ./windows/prepare-artifact.ps1 # produces artifacts/*.dll

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: tdlib.windows
          path: artifacts/*

  test-ubuntu1804:
    needs: build-linux
    runs-on: ubuntu-20.04
    container: ubuntu:18.04
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
      PACKAGE_VERSION_BASE: 1.8.1.0
    steps:
      - name: Set up Git
        run: apt-get update && apt-get install -y software-properties-common && apt-get update && add-apt-repository -y ppa:git-core/ppa && apt-get update && apt-get install -y git

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up PowerShell
        run: sh ./linux/install-pwsh.sh

      - name: Install
        shell: pwsh
        run: ./linux/install.ps1 -ForTests

      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: tdlib.linux
          path: ./artifacts

      - name: Copy artifacts
        shell: pwsh
        run: ./linux/copy-artifacts.ps1
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.x'
      - name: Pack NuGet
        shell: pwsh
        run: ./common/nuget-pack.ps1 -Version "${{ env.PACKAGE_VERSION_BASE }}" -NuGet $env:GITHUB_WORKSPACE/tools/nuget.exe -UseMono
        # TODO: Add ${{ github.run_id }} as a patch version

      - name: NuGet cache
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('tdsharp/**/*.csproj') }}
      - name: Test
        shell: pwsh
        run: ./common/test.ps1 -NuGet $env:GITHUB_WORKSPACE/tools/nuget.exe -UseMono

  test-macos:
    needs: build-macos
    runs-on: macos-10.15
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
      PACKAGE_VERSION_BASE: 1.8.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Download macOS artifact
        uses: actions/download-artifact@v2
        with:
          name: tdlib.osx
          path: ./artifacts

      - name: Copy artifacts
        shell: pwsh
        run: ./macos/copy-artifacts.ps1
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.x'
      - name: Pack NuGet
        shell: pwsh
        run: ./common/nuget-pack.ps1 -Version "${{ env.PACKAGE_VERSION_BASE }}" -NuGet nuget
        # TODO: Add ${{ github.run_id }} as a patch version

      - name: NuGet cache
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('tdsharp/**/*.csproj') }}
      - name: Test
        shell: pwsh
        run: ./common/test.ps1 -NuGet nuget

  test-windows:
    needs: build-windows
    runs-on: windows-2019
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
      PACKAGE_VERSION_BASE: 1.8.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Download Windows artifact
        uses: actions/download-artifact@v2
        with:
          name: tdlib.windows
          path: ./artifacts

      - name: Copy artifacts
        shell: pwsh
        run: ./windows/copy-artifacts.ps1
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.x'
      - name: Pack NuGet
        shell: pwsh
        run: ./common/nuget-pack.ps1 -Version "${{ env.PACKAGE_VERSION_BASE }}" -NuGet nuget
        # TODO: Add ${{ github.run_id }} as a patch version

      - name: NuGet cache
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('tdsharp/**/*.csproj') }}
      - name: Test
        shell: pwsh
        run: ./common/test.ps1 -NuGet nuget

  release:
    runs-on: ubuntu-20.04
    needs:
      - build-linux
      - build-macos
      - build-windows
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: tdlib.linux
          path: ./artifacts/linux
      - name: Archive Linux artifact
        shell: pwsh
        run: Set-Location ./artifacts/linux && zip -r ./tdlib.linux.zip *

      - name: Download macOS artifact
        uses: actions/download-artifact@v2
        with:
          name: tdlib.osx
          path: ./artifacts/osx
      - name: Archive macOS artifact
        shell: pwsh
        run: Set-Location ./artifacts/osx && zip -r ./tdlib.osx.zip *

      - name: Download Windows artifact
        uses: actions/download-artifact@v2
        with:
          name: tdlib.windows
          path: ./artifacts/windows
      - name: Archive Windows artifact
        shell: pwsh
        run: Set-Location ./artifacts/windows && zip -r ./tdlib.windows.zip *

      - name: Read version from ref
        if: startsWith(github.ref, 'refs/tags/v')
        id: version
        shell: pwsh
        run: Write-Output "::set-output name=version::$($env:GITHUB_REF -replace '^refs/tags/v', '')"

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ steps.version.outputs.version }}
          draft: true
      - name: Upload Linux artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: tdlib.linux.zip
          asset_path: ./artifacts/linux/tdlib.linux.zip
          asset_content_type: application/zip
      - name: Upload macOS artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: tdlib.osx.zip
          asset_path: ./artifacts/osx/tdlib.osx.zip
          asset_content_type: application/zip
      - name: Upload Windows artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: tdlib.windows.zip
          asset_path: ./artifacts/windows/tdlib.windows.zip
          asset_content_type: application/zip
